'use strict'

module.exports = {
  equals: require('./equals'),
  equalsWith: require('./equalsWith'),
  filter: require('./filter'),
  find: require('./find'),
  findEntry: require('./findEntry'),
  findKey: require('./findKey'),
  findLast: require('./findLast'),
  findLastEntry: require('./findLastEntry'),
  findLastKey: require('./findLastKey'),
  forEach: require('./forEach'),
  isObjectLike: require('./isObjectLike'),
  map: require('./map'),
  mapEntries: require('./mapEntries'),
  mapKeys: require('./mapKeys'),
  merge: require('./merge'),
  mergeWith: require('./mergeWith'),
  omit: require('./omit'),
  pick: require('./pick'),
  reduce: require('./reduce'),
  reduceRight: require('./reduceRight'),
  remove: require('./remove'),
  set: require('./set'),
  size: require('./size'),
  some: require('./some'),
  zip: require('./zip'),
  zipWith: require('./zipWith')
}